### PR TITLE
use logger.language

### LINKED ISSUE #3: c::set('logger.language', 'de') has no effect
I tried `c::set('logger.language', 'de');` but the language still is english

### PR DESCRIPTION
**Pull request by mxub**
as I understand it this should fix #3

### CODE REVIEW

**Comment by mxub** [comment]
maybe one should only use the helper function ?

**Comment by mxub** [comment]
## Explanation 

c149289 is the fix to use logger.language (if set)

accbdc1 & ccad7ed DRY up `helper.php` and `logger.php` to only use the `translation()`-method from `helper.php`

**Comment by texnixe** [comment]
I finally got round to testing this, but I get an error message (
Use of undefined constant translation - assumed 'translation').

**Comment by mxub** [comment]
found it - had it in my live site fixed but not in the patch repository - sorry

**Pull request merged**
